### ISSUE TITLE
Hero Image - black background on floating boxes

### ISSUE THREAD

**Issue by berkid89** [MessageSilo/Website#1]
![image](https://github.com/MessageSilo/Website/assets/16096587/6d79cb9f-a541-41aa-81be-7849d3b8da7b)

**Comment by GazdagB** [comment]
![image](https://github.com/MessageSilo/Website/assets/130493030/3ad84c02-d44d-4ed3-a69d-dcbe41f36d4a)

Made some improvements on the svg file
