### ISSUE TITLE
Top nav - add "half transparent background" like in mobile view

### ISSUE THREAD

**Issue by berkid89** [MessageSilo/Website#3]
![image](https://github.com/MessageSilo/Website/assets/16096587/8b7a59e1-88ce-42a5-a7e4-ef70662e10ce)

like here:
![image](https://github.com/MessageSilo/Website/assets/16096587/e8c69e51-5ea7-47d3-8d14-e40683c72a49)

**Comment by GazdagB** [comment]
When page is not scrolled the navigation is transparent: 
<img width="1915" alt="image" src="https://github.com/MessageSilo/Website/assets/130493030/43984fd4-84ae-4efb-877e-852748cdba63">

When the page is scrolled it gets the same background effect as on mobile: 
<img width="1907" alt="image" src="https://github.com/MessageSilo/Website/assets/130493030/c84afd6b-60fd-45f7-abb9-2b98d37b3bd5">
